
#define _CRT_SECURE_NO_WARNINGS

#include <stdio.h>
#include <stdlib.h>
#include "include/file-io.h"

/*
	Reading From File

	FUNCTIONS:

	> FileReadAllText()
	Reads all of the text contents of a file into a string
	Error will be raised if the file failed to read
	
	WARNING:

	Attempting to access a string generated by FileReadAllText() when the function returned an error may result
	in a runtime error. This function should be checked when it is called for errors. 
*/

Error* FileReadAllText(const char* path, const char** text) {
	FILE* file = fopen(path, "rb");

	if (file == NULL) {
		CREATE_ERROR(ERR_ACCESS_PATH_FAILURE, path);
		return error;
	}

	fseek(file, 0, SEEK_END);
	long size = ftell(file);
	fseek(file, 0, SEEK_SET);

	char* _text = malloc(size + 1);
	fread(_text, size, 1, file);
	fclose(file);

	_text[size] = '\0';
	*text = _text;
	return NO_ERROR;
}

/*
	Writing To File

	FUNCTIONS:

	> FileWriteAllText()
	Writes an entire string to a file
	Error will be raised if the file failed to write
*/

Error* FileWriteAllText(const char* path, const char* text) {
	FILE* file = fopen(path, "w");

	if (file == NULL) {
		CREATE_ERROR(ERR_ACCESS_PATH_FAILURE, path);
		return error;
	}

	if (file != NULL) {
		fputs(text, file);
		fclose(file);
	}

	return NO_ERROR;
}
